repos:
  - repo: local
    hooks:
      - id: black-check
        name: black-check
        entry: make black-check
        language: system
        always_run: true
        pass_filenames: false
      - id: isort-check
        name: isort-check
        entry: make isort-check
        language: system
        always_run: true
        pass_filenames: false