name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-in-project: true
      - uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('**/poetry.lock') }}
      - name: Setup Virtualenv
        run: poetry install
      - name: Lint
        run: poetry run make flake black-check isort-check
      - name: Test
        run: poetry run make tests
      - name: Upload Coverage
        run: poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: py${{ matrix.python }}
          COVERALLS_PARALLEL: true

  coverage:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Finalise Coverage
        run: pip3 install --upgrade coveralls && coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
